//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRestGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointRepere
    {
        public int Idrepere { get; set; }
        public string Quartier { get; set; }
        public string Commune { get; set; }
        public string Departement { get; set; }
        public string Region { get; set; }
    }
}
